# Generated by Django 5.2.13 on 2026-05-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cancion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("artista", models.CharField(max_length=100)),
                ("foto_url", models.URLField(blank=True, max_length=500, null=True)),
                ("album", models.CharField(blank=True, max_length=100, null=True)),
                ("genero", models.CharField(default="Pop", max_length=50)),
                ("letra", models.TextField(blank=True, null=True)),
                ("fecha_agregada", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cancion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="blog.cancion",
                    ),
                ),
            ],
        ),
    ]
