services:
  - type: web
    name: playlist-aesthetic
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn hello_world.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1